# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0002_remove_traindata_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.TextField()),
                ('review_text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.ColorCode')),
                ('sentiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Sentiment')),
            ],
        ),
    ]
