# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20161114_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='sentiment',
            field=models.TextField(),
        ),
    ]
