# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='asin',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
