# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.TextField()),
                ('review_text', models.TextField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.ColorCode')),
                ('sentiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Sentiment')),
            ],
        ),
    ]
