# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='asin',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
