# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161123_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='asin',
            field=models.TextField(max_length=10),
        ),
    ]
